---
title: "Atlas de servicios ecosistémicos de la GAM - Documentación"
author: "Manuel Vargas"
date: "2020-07-07"
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false    
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
```

# Recursos de interés
* Repositorios en GitHub del Atlas de Servicios Ecosistémicos de la GAM: [https://github.com/atlas-servicios-ecosistemicos-gam](https://github.com/atlas-servicios-ecosistemicos-gam).
* Sitio web del lenguaje de programación R: [The R Project for Statistical Computing](https://www.r-project.org/).
* Sitio web del entorno de desarrollo RStudio: [RStudio | Open source & professional software for data science teams](https://rstudio.com/).

* Sitio web del paquete Flexdashboard de R: [Flexdashboard: Easy interactive dashboards for R](https://rmarkdown.rstudio.com/flexdashboard/).
* Sitio web del paquete Leaflet para R: [Leaflet for R](https://rstudio.github.io/leaflet/).
* Sitio web del paquete Plotly para R: [Plotly R Open Source Graphing Library](https://plotly.com/r/).
* Sitio web del paquete DT para R: [DT: An R interface to the DataTables library](https://rstudio.github.io/DT/).
* Libro "R Markdown: The Definitive Guide", de Xie et al.: [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/).

# Presentación
Este documento contiene la documentación técnica del [Atlas de Servicios Ecosistémicos de la Gran Área Metropolitana (GAM)](https://github.com/atlas-servicios-ecosistemicos-gam). El objetivo de su elaboración es facilitar la instalación, modificación y mantenimiento del Atlas por parte de cualquier persona u organización interesada.

# Introducción
El Atlas de Servicios Ecosistémicos de la GAM está siendo implementado como un portal web que permite la visualización y el análisis de datos geoespaciales. Su desarrollo se ubica en el contexto del proyecto [Biodiver_City](http://biocorredores.org/biodiver-city-sanjose/), el cual tiene como objetivo que las instituciones públicas (ej. Minae, Sinac, municipalidades) y actores claves privados (ej. sector empresarial, organizaciones no gubernamentales, iniciativas urbanas) incorporen los servicios ecosistémicos urbanos y el establecimiento y la gestión de corredores biológicos interurbanos en su planificación de desarrollo. El proyecto acompañará de cerca a los corredores biológicos interurbanos (CBI) María Aguilar y Río Torres. El desarrollo del Atlas es parte de la actividad “Análisis de los servicios ecosistémicos de los espacios verdes en la Gran Área Metropolitana (GAM) de Costa Rica”, ejecutada por el Centro Agronómico Tropical de Investigación y Enseñanza (Catie).

El Atlas presenta los datos relacionados con diferentes indicadores de servicios ecosistémicos de la GAM, entre los que pueden mencionarse:

* Uso del suelo.
* Zonas urbanas.
* Cobertura de vegetación.
* Superficie de tierra cultivada.
* Superficie de pastos.
* Superficie verde.
* Islas de calor.
* Biodiversidad.
* Áreas silvestres protegidas.
* Energía hidroeléctrica.
* Conectividad ecológica.

Los indicadores pueden presentarse a nivel de toda la GAM, de CBI o de cantón.

# Tecnologías informáticas utilizadas
Para implementar el Atlas, se utiliza un conjunto de tecnologías relacionadas con el lenguaje de programación [R](https://www.r-project.org/) y su entorno de desarrollo asociado [RStudio](https://rstudio.com/). R es un lenguaje de programación enfocado en análisis estadístico y muy popular en aplicaciones científicas y de código abierto. Está apoyado por una comunidad de programadores que continuamente amplían su funcionalidad a través de diferentes formas, entre las que destaca la implementación de [paquetes](https://rstudio.com/products/rpackages/). Los paquetes son unidades de código en R que se desarrollan, instalan, documentan y mantienen de manera independente de la base de R con diversos fines (estadística, graficación, aprendizaje automatizado, etc.)

Las principales tecnologías relacionadas con el lenguaje R que se utilizan en la implementación del Atlas son:

* La sintaxis [R Markdown](https://rmarkdown.rstudio.com/). Permite intercalar código fuente en R (y otros lenguajes de programación) con texto, gráficos, tablas, mapas y otros tipos de contenido. Los documentos R Markdown son completamente reproducibles y ampliamente usados en comunicación científica.

* El paquete [Flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/) de R. Utiliza R Markdown para generar tableros de control (también llamados _cuadros de mando_) que integran diversas visualizaciones de conjuntos de datos tales como gráficos, tablas y mapas. Opcionalmente, puede utilizar el paquete [Shiny](https://shiny.rstudio.com/) para brindar mayor interactividad.

* El paquete [Leaflet para R](https://rstudio.github.io/leaflet/). Es una implementación en R de la biblioteca [Leaflet para el lenguaje JavaScript](https://leafletjs.com/) para la programación de mapas interactivos en páginas web. Los mapas de Leaflet pueden incluirse en documentos R Markdown y en aplicaciones de Flexdashboard y Shiny.

* El paquete [Plotly para R](https://plotly.com/r/). Es una biblioteca para gráficos interactivos para la web, basada en la biblioteca [plotly.js](https://github.com/plotly/plotly.js) de JavaScript.

* El paquete [DT para R](https://rstudio.github.io/DT/). Proporciona una interfaz en R para la biblioteca [DataTables](http://datatables.net/) en JavaScript. A través de DT, los objetos de datos de R (ej. _data frames_) pueden ser desplegados como tablas en páginas web, con capacidades de filtrado, paginación y ordenación, entre otras.